/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_unicef_cboard_MCD_LanguageInfo */

#ifndef _Included_com_unicef_cboard_MCD_LanguageInfo
#define _Included_com_unicef_cboard_MCD_LanguageInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unicef_cboard_MCD_RHVoiceException */

#ifndef _Included_com_unicef_cboard_MCD_RHVoiceException
#define _Included_com_unicef_cboard_MCD_RHVoiceException
#ifdef __cplusplus
extern "C" {
#endif
#undef com_unicef_cboard_MCD_RHVoiceException_serialVersionUID
#define com_unicef_cboard_MCD_RHVoiceException_serialVersionUID -3042686055658047285LL
#undef com_unicef_cboard_MCD_RHVoiceException_serialVersionUID
#define com_unicef_cboard_MCD_RHVoiceException_serialVersionUID -3387516993124229948LL
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unicef_cboard_MCD_SynthesisParameters */

#ifndef _Included_com_unicef_cboard_MCD_SynthesisParameters
#define _Included_com_unicef_cboard_MCD_SynthesisParameters
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unicef_cboard_MCD_TTSClient */

#ifndef _Included_com_unicef_cboard_MCD_TTSClient
#define _Included_com_unicef_cboard_MCD_TTSClient
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unicef_cboard_MCD_TTSEngine */

#ifndef _Included_com_unicef_cboard_MCD_TTSEngine
#define _Included_com_unicef_cboard_MCD_TTSEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_unicef_cboard_MCD_TTSEngine
 * Method:    onClassInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unicef_cboard_MCD_TTSEngine_onClassInit
  (JNIEnv *, jclass);

/*
 * Class:     com_unicef_cboard_MCD_TTSEngine
 * Method:    onInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;Lcom/unicef/cboard/MCD/Logger)V
 */
JNIEXPORT void JNICALL Java_com_unicef_cboard_MCD_TTSEngine_onInit
(JNIEnv *, jobject, jstring, jstring, jobjectArray, jstring, jobject);

/*
 * Class:     com_unicef_cboard_MCD_TTSEngine
 * Method:    onShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_unicef_cboard_MCD_TTSEngine_onShutdown
  (JNIEnv *, jobject);

/*
 * Class:     com_unicef_cboard_MCD_TTSEngine
 * Method:    doGetVoices
 * Signature: ()[Lcom/unicef/cboard/MCD/VoiceInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_com_unicef_cboard_MCD_TTSEngine_doGetVoices
  (JNIEnv *, jobject);

/*
 * Class:     com_unicef_cboard_MCD_TTSEngine
 * Method:    doSpeak
 * Signature: (Ljava/lang/String;Lcom/unicef/cboard/MCD/SynthesisParameters;Lcom/unicef/cboard/MCD/TTSClient;)V
 */
JNIEXPORT void JNICALL Java_com_unicef_cboard_MCD_TTSEngine_doSpeak
  (JNIEnv *, jobject, jstring, jobject, jobject);

/*
 * Class:     com_unicef_cboard_MCD_TTSEngine
 * Method:    doConfigure
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_unicef_cboard_MCD_TTSEngine_doConfigure
(JNIEnv *, jobject, jstring, jstring);

JNIEXPORT jstring JNICALL Java_com_unicef_cboard_MCD_TTSEngine_doGetCachedPackageDir
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_com_unicef_cboard_MCD_TTSEngine_doGetPackageDirFromServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_unicef_cboard_MCD_VoiceInfo */

#ifndef _Included_com_unicef_cboard_MCD_VoiceInfo
#define _Included_com_unicef_cboard_MCD_VoiceInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
